apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: observability
  labels:
    grafana_datasource: "true"
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        uid: 26520287B2594D8C9248
        type: prometheus
        access: proxy
        url: "http://loki-gateway.observability/loki"
        isDefault: false
        editable: false
        jsonData:
          maxLines: 1000