apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: observability
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
        isDefault: true
        jsonData:
          maxLines: 1000
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prom:9090
        isDefault: false
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: loki
          serviceMap:
            datasourceUid: tempo