mimir-distributed:
  nameOverride: mimir
  fullnameOverride: mimir

  alertmanager:
    enabled: false

  query_frontend:
    extraArgs:
      log.level: debug

  query_scheduler:
    enabled: false

  runtimeConfig:
    distributor_limits:
      max_ingestion_rate: 50000
#  distributor:
#    extraArgs:
#      "-distributor.ingestion-rate-limit=50000"
#      "-distributor.ingestion-burst-size=500000"

  ingester:
    # -- Total number of replicas for the store-gateway across all availability zones
    # If store_gateway.zoneAwareReplication.enabled=false, this number is taken as is.
    # Otherwise each zone starts `ceil(replicas / number_of_zones)` number of pods.
    #   E.g. if 'replicas' is set to 4 and there are 3 zones, then 4/3=1.33 and after rounding up it means 2 pods per zone are started.
    replicas: 2
    # zoneAwareReplication is true by default, and there are 3 zone: zone-a, zone-b and zone-c, it will create the replicas to each zone
    # mimir-ingester-zone-a-0
    # mimir-ingester-zone-b-0
    # mimir-ingester-zone-c-0
    zoneAwareReplication:
      enabled: false
    extraArgs:
      log.level: debug

  store_gateway:
    # -- Total number of replicas for the store-gateway across all availability zones
    # If store_gateway.zoneAwareReplication.enabled=false, this number is taken as is.
    # Otherwise each zone starts `ceil(replicas / number_of_zones)` number of pods.
    #   E.g. if 'replicas' is set to 4 and there are 3 zones, then 4/3=1.33 and after rounding up it means 2 pods per zone are started.
    replicas: 1
    # zoneAwareReplication is true by default, and there are 3 zone: zone-a, zone-b and zone-c, it will create the replicas to each zone
    # mimir-ingester-zone-a-0
    # mimir-ingester-zone-b-0
    # mimir-ingester-zone-c-0
    zoneAwareReplication:
      enabled: false