grafana:
  adminPassword: "admin-1234"
  initChownData:
    enabled: false

  persistence:
    enabled: true
    size: 5Gi
    storageClassName: "standard"

  podSecurityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
    fsGroupChangePolicy: "OnRootMismatch"

  securityContext:
    runAsUser: 472
    runAsGroup: 472

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      searchNamespace: ALL
    datasources:
      enabled: true
      label: grafana_datasource
      searchNamespace: ALL

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Mimir
        uid: 45CC07CEF6D74D91BE989
        type: prometheus
        access: proxy
        url: "http://mimir-nginx.observability/prometheus"
        isDefault: true
        editable: false
        jsonData:
          httpMethod: POST
          timeInterval: 30s
#      - name: Prometheus
#        uid: 464EDC8622694ECA9847
#        type: prometheus
#        access: proxy
#        url: "http://prometheus-prometheus.observability:9090"
#        editable: false
#        isDefault: false
#        jsonData:
#          timeInterval: "30s"
#          httpMethod: GET