mimir-distributed:
  adminPassword: "admin-1234"

  nameOverride: mimir
  fullnameOverride: mimir

  alertmanager:
    enabled: false

  ingester:
    # -- Total number of replicas for the store-gateway across all availability zones
    # If store_gateway.zoneAwareReplication.enabled=false, this number is taken as is.
    # Otherwise each zone starts `ceil(replicas / number_of_zones)` number of pods.
    #   E.g. if 'replicas' is set to 4 and there are 3 zones, then 4/3=1.33 and after rounding up it means 2 pods per zone are started.
    replicas: 1
    # zoneAwareReplication is true by default, and there are 3 zone: zone-a, zone-b and zone-c, it will create the replicas to each zone
    # mimir-ingester-zone-a-0
    # mimir-ingester-zone-b-0
    # mimir-ingester-zone-c-0
    zoneAwareReplication:
      enabled: false

  store_gateway:
    # -- Total number of replicas for the store-gateway across all availability zones
    # If store_gateway.zoneAwareReplication.enabled=false, this number is taken as is.
    # Otherwise each zone starts `ceil(replicas / number_of_zones)` number of pods.
    #   E.g. if 'replicas' is set to 4 and there are 3 zones, then 4/3=1.33 and after rounding up it means 2 pods per zone are started.
    replicas: 1
    # zoneAwareReplication is true by default, and there are 3 zone: zone-a, zone-b and zone-c, it will create the replicas to each zone
    # mimir-ingester-zone-a-0
    # mimir-ingester-zone-b-0
    # mimir-ingester-zone-c-0
    zoneAwareReplication:
      enabled: false

  persistence:
    enabled: true
    size: 5Gi
    storageClassName: "standard"

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      searchNamespace: ALL
    datasources:
      enabled: true
      label: grafana_datasource
      searchNamespace: ALL

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Mimir
          type: prometheus
          access: proxy
          url: http://mimir-gateway.observability/prometheus
          isDefault: true
          jsonData:
            httpMethod: POST
            timeInterval: 30s
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-prometheus.observability:9090
          isDefault: false