apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-datasource
  namespace: observability
  labels:
    grafana_datasource: "true"
data:
  datasource-config.yaml: |
    apiVersion: 1
    datasources:
      - name: Mimir
        uid: 45CC07CEF6D74D91BE989
        type: prometheus
        access: proxy
        url: "http://mimir-nginx.observability/prometheus"
        isDefault: true
        editable: false
        jsonData:
          httpMethod: POST
          timeInterval: 30s